#!/usr/bin/env python

import logging

from scasa import scasa
from scasa import cli


def main():
    args = cli.parse_args()

    logging.basicConfig(
        level=logging.INFO if args.verbose else logging.WARNING,
        format="%(message)s",
    )

    pdb_complex = scasa.Complex(args.infile, args.complex_1, args.complex_2,
                                distance=args.distance, plot=args.plot)
    if args.command == "asa":
        pdb_complex.create_sub_pdbs()
        pdb_complex.complex_sasa()
    if args.command == "sc":
        pdb_complex.sc()


if __name__ == "__main__":
    main()
